module.exports = {
	STARTED: process.env.DATABASE_STATUS_STARTED,
	PENDING: process.env.DATABASE_STATUS_PENDING,
	APPROVED: process.env.DATABASE_STATUS_APPROVED,
	REJECTED: process.env.DATABASE_STATUS_REJECTED,
};